/**
 * Tool slug → brand logo file in `public/logos/` (VIB-164).
 *
 * Curated, not fetched: most skills and several tools link to github.com, so
 * a favicon lookup would badge them all with the GitHub mark. Marks come from
 * Simple Icons (CC0), LobeHub Icons (MIT), or the brand's own site icon or
 * GitHub org avatar where neither set has one. A skill gets its publisher's
 * mark only when the brand's own org ships it (vercel-labs, supabase, aws);
 * personal repos have no official identity and keep the generic icon.
 *
 * A slug missing here falls back to the generic icon. To add one, drop the
 * file in public/logos and add the line with its extension.
 */
export const TOOL_LOGOS: Record<string, string> = {
  "agent-skills": "claude.svg",
  aider: "aider.png",
  alacritty: "alacritty.svg",
  "android-studio": "androidstudio.svg",
  "anthropic-skills": "anthropic.svg",
  "athena-data-lake": "aws-color.svg",
  autogen: "microsoft-color.svg",
  "awesome-claude-skills": "composio.png",
  "awesome-skills": "awesomeskill.png",
  "aws-amplify": "aws-color.svg",
  "aws-deployment": "aws-color.svg",
  "aws-secrets": "aws-color.svg",
  "aws-serverless": "aws-color.svg",
  "azure-kubernetes": "azure-color.svg",
  base44: "base44.png",
  bolt: "bolt.svg",
  bubble: "bubble.jpg",
  "canvas-design": "anthropic.svg",
  capafy: "capafy.png",
  chatgpt: "openai.svg",
  "chatgpt-sites": "openai.svg",
  claude: "claude.svg",
  "claude-agent-sdk": "claude.svg",
  "claude-ai": "claude.svg",
  "claude-code": "claudecode.svg",
  "claude-design": "claude.svg",
  clickup: "clickup.svg",
  "cloudflare-security-audit": "cloudflare.svg",
  "cloudflare-workers": "cloudflareworkers.svg",
  "coderabbit-code-review": "coderabbit.svg",
  codex: "codex-color.svg",
  continue: "continue.png",
  "copilot-coding-agent": "githubcopilot.svg",
  "create-t3-app": "create-t3-app.svg",
  crewai: "crewai-color.svg",
  cursor: "cursor.svg",
  "deploy-to-vercel": "vercel.svg",
  devin: "devin-color.svg",
  "devin-desktop": "devin-color.svg",
  "differential-review": "trailofbits.png",
  "digitalocean-app-platform": "digitalocean.svg",
  "doc-coauthoring": "anthropic.svg",
  "docx-skill": "anthropic.svg",
  "dotnet-performance": "dotnet.svg",
  emergent: "emergent.png",
  "fastapi-skill": "fastapi.svg",
  "figma-make": "figma-color.svg",
  "firebase-hosting": "firebase.svg",
  "firecrawl-mcp": "firecrawl-color.svg",
  flutterflow: "flutterflow.png",
  "fly-io": "flydotio.svg",
  framer: "framer.svg",
  "frontend-design": "anthropic.svg",
  gemini: "gemini-color.svg",
  "gemini-cli": "geminicli-color.svg",
  ghostty: "ghostty.svg",
  "git-bash": "gitforwindows.svg",
  "github-copilot": "githubcopilot.svg",
  "github-mcp-server": "github.svg",
  "github-pages": "github.svg",
  "google-adk": "adk.png",
  "google-ai-studio": "aistudio.svg",
  "google-antigravity": "antigravity-color.svg",
  gpt: "openai.svg",
  graphify: "graphify.png",
  higgsfield: "higgsfield.png",
  hostinger: "hostinger.svg",
  "hyperframes-slideshow": "heygen.ico",
  "intellij-idea": "intellijidea.svg",
  "internal-comms": "anthropic.svg",
  iterm2: "iterm2.svg",
  jules: "jules.png",
  "just-scrape": "scrapegraphai.png",
  "kilo-code": "kilocode.svg",
  kiro: "kiro-color.svg",
  kitty: "kitty.svg",
  konsole: "kde.svg",
  langchain: "langchain.svg",
  langgraph: "langgraph-color.svg",
  "linear-mcp": "linear.svg",
  lovable: "lovable-color.svg",
  "macos-terminal": "macos.svg",
  mastra: "mastra.svg",
  "microsoft-agent-framework": "microsoft-color.svg",
  n8n: "n8n-color.svg",
  "neon-postgres-skill": "neon.svg",
  netlify: "netlify.svg",
  "netlify-mcp": "netlify.svg",
  nextjs: "nextdotjs.svg",
  "notion-mcp": "notion.svg",
  "openai-agents-sdk": "openai.svg",
  opencode: "opencode.svg",
  openrouter: "openrouter.svg",
  "playwright-mcp": "playwright.svg",
  powershell: "powershell.png",
  "pptx-skill": "anthropic.svg",
  "prisma-database-setup": "prisma.svg",
  "product-launch-video": "heygen.ico",
  promptbase: "promptbase.png",
  railway: "railway.svg",
  "react-native-best-practices": "vercel.svg",
  "redshift-guide": "aws-color.svg",
  relume: "relume.png",
  render: "render.svg",
  replit: "replit.svg",
  resend: "resend.svg",
  "sentry-code-review": "sentry.svg",
  "sentry-fix-issues": "sentry.svg",
  "shadcn-skill": "shadcnui.svg",
  "shadcn-ui": "shadcnui.svg",
  skild: "skild.svg",
  skillkit: "skillkit.svg",
  "skills-cli": "vercel.svg",
  "skills-sh": "skills-sh.ico",
  skillsmp: "skillsmp.png",
  slack: "slack.png",
  softr: "softr.png",
  supabase: "supabase.svg",
  "supabase-mcp-server": "supabase.svg",
  "supabase-postgres-best-practices": "supabase.svg",
  "supabase-skill": "supabase.svg",
  "supply-chain-risk-auditor": "trailofbits.png",
  tabby: "tabby.png",
  "test-anti-patterns": "dotnet.svg",
  trae: "trae-color.svg",
  "turnstile-spin": "cloudflare.svg",
  typesense: "typesense.png",
  v0: "v0.svg",
  vercel: "vercel.svg",
  "vercel-composition-patterns": "vercel.svg",
  "vercel-mcp": "vercel.svg",
  "vercel-react-best-practices": "vercel.svg",
  "vs-code": "vscode.png",
  warp: "warp.svg",
  "wave-terminal": "waveterm.png",
  "web-design-guidelines": "vercel.svg",
  "webapp-testing": "anthropic.svg",
  webflow: "webflow.svg",
  webstorm: "webstorm.svg",
  wezterm: "wezterm.svg",
  "windows-terminal": "windowsterminal.svg",
  wrangler: "cloudflare.svg",
  xcode: "xcode.svg",
  "xlsx-skill": "anthropic.svg",
  zapier: "zapier-color.svg",
  zed: "zedindustries.svg",
};

export function toolLogoSrc(slug: string): string | null {
  const file = TOOL_LOGOS[slug];
  return file ? `/logos/${file}` : null;
}
