/**
 * Tool slug → brand logo file in `public/logos/` (VIB-164).
 *
 * Curated, not fetched: most skills and several tools link to github.com, so
 * a favicon lookup would badge them all with the GitHub mark. Marks come from
 * Simple Icons (CC0) and LobeHub Icons (MIT). A skill gets its publisher's
 * mark only when the brand's own org ships it (vercel-labs, supabase, aws);
 * personal repos have no official identity and keep the generic icon.
 *
 * A slug missing here falls back to the generic icon. To add one, drop the
 * SVG in public/logos and add the line.
 */
export const TOOL_LOGOS: Record<string, string> = {
  "agent-skills": "claude",
  alacritty: "alacritty",
  "android-studio": "androidstudio",
  "anthropic-skills": "anthropic",
  "athena-data-lake": "aws-color",
  autogen: "microsoft-color",
  "aws-amplify": "aws-color",
  "aws-deployment": "aws-color",
  "aws-secrets": "aws-color",
  "aws-serverless": "aws-color",
  "azure-kubernetes": "azure-color",
  "canvas-design": "anthropic",
  chatgpt: "openai",
  "chatgpt-sites": "openai",
  claude: "claude",
  "claude-agent-sdk": "claude",
  "claude-ai": "claude",
  "claude-code": "claudecode",
  "claude-design": "claude",
  clickup: "clickup",
  "cloudflare-security-audit": "cloudflare",
  "cloudflare-workers": "cloudflareworkers",
  "coderabbit-code-review": "coderabbit",
  codex: "codex-color",
  "copilot-coding-agent": "githubcopilot",
  crewai: "crewai-color",
  cursor: "cursor",
  "deploy-to-vercel": "vercel",
  devin: "devin-color",
  "devin-desktop": "devin-color",
  "digitalocean-app-platform": "digitalocean",
  "doc-coauthoring": "anthropic",
  "docx-skill": "anthropic",
  "dotnet-performance": "dotnet",
  "fastapi-skill": "fastapi",
  "figma-make": "figma-color",
  "firebase-hosting": "firebase",
  "firecrawl-mcp": "firecrawl-color",
  "fly-io": "flydotio",
  framer: "framer",
  "frontend-design": "anthropic",
  gemini: "gemini-color",
  "gemini-cli": "geminicli-color",
  ghostty: "ghostty",
  "git-bash": "gitforwindows",
  "github-copilot": "githubcopilot",
  "github-mcp-server": "github",
  "github-pages": "github",
  "google-adk": "google",
  "google-ai-studio": "aistudio",
  "google-antigravity": "antigravity-color",
  gpt: "openai",
  hostinger: "hostinger",
  "intellij-idea": "intellijidea",
  "internal-comms": "anthropic",
  iterm2: "iterm2",
  jules: "googlejules",
  "kilo-code": "kilocode",
  kiro: "kiro-color",
  konsole: "kde",
  langchain: "langchain",
  langgraph: "langgraph-color",
  "linear-mcp": "linear",
  lovable: "lovable-color",
  "macos-terminal": "macos",
  mastra: "mastra",
  "microsoft-agent-framework": "microsoft-color",
  n8n: "n8n-color",
  "neon-postgres-skill": "neon",
  netlify: "netlify",
  "netlify-mcp": "netlify",
  nextjs: "nextdotjs",
  "notion-mcp": "notion",
  "openai-agents-sdk": "openai",
  opencode: "opencode",
  openrouter: "openrouter",
  "pptx-skill": "anthropic",
  "prisma-database-setup": "prisma",
  railway: "railway",
  "react-native-best-practices": "vercel",
  "redshift-guide": "aws-color",
  render: "render",
  replit: "replit",
  resend: "resend",
  "sentry-code-review": "sentry",
  "sentry-fix-issues": "sentry",
  "shadcn-skill": "shadcnui",
  "shadcn-ui": "shadcnui",
  "skills-cli": "vercel",
  supabase: "supabase",
  "supabase-mcp-server": "supabase",
  "supabase-postgres-best-practices": "supabase",
  "supabase-skill": "supabase",
  "test-anti-patterns": "dotnet",
  trae: "trae-color",
  "turnstile-spin": "cloudflare",
  v0: "v0",
  vercel: "vercel",
  "vercel-composition-patterns": "vercel",
  "vercel-mcp": "vercel",
  "vercel-react-best-practices": "vercel",
  warp: "warp",
  "web-design-guidelines": "vercel",
  "webapp-testing": "anthropic",
  webflow: "webflow",
  webstorm: "webstorm",
  wezterm: "wezterm",
  wrangler: "cloudflare",
  xcode: "xcode",
  "xlsx-skill": "anthropic",
  zapier: "zapier-color",
  zed: "zedindustries",
};

export function toolLogoSrc(slug: string): string | null {
  const file = TOOL_LOGOS[slug];
  return file ? `/logos/${file}.svg` : null;
}
